### ISSUE TITLE
\otimes isn't rendered correctly in a paragraph

### ISSUE THREAD

**Issue by artagnon** [sonoisa/XyJax-v3#1]
Testcase: $M_1 \otimes M_2$ in a paragraph. The top part of the line is clipped in the rendering:

<img width="95" alt="Capture d’écran 2021-02-28 à 12 39 49" src="https://user-images.githubusercontent.com/37226/109417022-181b7100-79c2-11eb-86f9-2cbce28d0c9f.png">

See [this page](https://artagnon.com/math/∞/outline) for a live example of this bug.

On second thought, this is probably a MathJax-v3 CHTML bug.

**Comment by artagnon** [comment]
See https://github.com/mathjax/MathJax/issues/2637

**Comment by MrAJay34** [comment]
> Testcase: M1⊗M2 in a paragraph. The top part of the line is clipped in the rendering:
> 
> <img alt="Capture d’écran 2021-02-28 à 12 39 49" width="95" src="https://user-images.githubusercontent.com/37226/109417022-181b7100-79c2-11eb-86f9-2cbce28d0c9f.png">
> 
> See [this page](https://artagnon.com/math/%E2%88%9E/outline) for a live example of this bug.
> 
> On second thought, this is probably a MathJax-v3 CHTML bug.
